# Generated by Django 3.0.8 on 2020-09-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.CharField(max_length=20, null=True)),
                ('manufacturer', models.TextField()),
                ('brand', models.CharField(max_length=10, null=True)),
                ('item_height', models.CharField(max_length=20, null=True)),
                ('item_width', models.CharField(max_length=20, null=True)),
                ('product_dimensions', models.CharField(max_length=20, null=True)),
                ('item_model_no', models.CharField(max_length=20, null=True)),
                ('series', models.CharField(max_length=20, null=True)),
                ('computer_memory_type', models.CharField(max_length=20, null=True)),
                ('batteries', models.CharField(max_length=20, null=True)),
                ('processor_socket', models.CharField(max_length=20, null=True)),
                ('graphics_card_interface', models.CharField(max_length=20, null=True)),
                ('no_of_USB', models.CharField(max_length=20, null=True)),
                ('are_batteries_included', models.CharField(max_length=20, null=True)),
                ('item_weight', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.CharField(max_length=20, null=True)),
                ('manufacturer', models.TextField()),
                ('brand', models.CharField(max_length=10, null=True)),
                ('item_height', models.CharField(max_length=20, null=True)),
                ('item_width', models.CharField(max_length=20, null=True)),
                ('product_dimensions', models.CharField(max_length=20, null=True)),
                ('item_model_no', models.CharField(max_length=20, null=True)),
                ('processor_brand', models.CharField(max_length=20, null=True)),
                ('processor_type', models.CharField(max_length=20, null=True)),
                ('processor_speed', models.CharField(max_length=20, null=True)),
                ('processor_socket', models.CharField(max_length=20, null=True)),
                ('processor_count', models.IntegerField()),
                ('ram_size', models.CharField(max_length=20, null=True)),
                ('computer_memory_type', models.CharField(max_length=20, null=True)),
                ('harddrive_size', models.CharField(max_length=20, null=True)),
                ('hard_drive_interface', models.CharField(max_length=20, null=True)),
                ('wattage', models.CharField(max_length=20, null=True)),
                ('hardware_platform', models.CharField(max_length=20, null=True)),
                ('operating_system', models.CharField(max_length=20, null=True)),
                ('are_batteries_included', models.CharField(max_length=20, null=True)),
                ('item_weight', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
