# Generated by Django 3.0.8 on 2020-09-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_auto_20200923_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='graphics_card',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='harddisk',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='liquid_cooling_system',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='os',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='power_supply_unit',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
