# Generated by Django 3.0.8 on 2020-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_auto_20200924_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='mounting_hardware',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='usb_ports',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='graphics_card',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='harddisk',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='liquid_cooling_system',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='liquid_cooling_system',
            name='processor_count',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='liquid_cooling_system',
            name='voltage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='power_supply_unit',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='power_supply_unit',
            name='processor_count',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='power_supply_unit',
            name='voltage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='form_factor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='included_components',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='memory_clock_speed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='memory_technology',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='voltage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
