# Generated by Django 3.0.8 on 2020-09-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_auto_20200924_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='processor_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
