# Generated by Django 3.0.8 on 2020-12-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0010_auto_20200924_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='graphics_card',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='harddisk',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='keyboard',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='liquid_cooling_system',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='motherboard',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='mouse',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='os',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='power_supply_unit',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['-price']},
        ),
        migrations.AddField(
            model_name='case',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graphics_card',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harddisk',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquid_cooling_system',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='os',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='power_supply_unit',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Case')),
                ('Graphics_Card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Graphics_Card')),
                ('Harddisk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Harddisk')),
                ('Keyboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Keyboard')),
                ('Liquid_Cooling_System', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Liquid_Cooling_System')),
                ('Monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Monitor')),
                ('Motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Motherboard')),
                ('Mouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Mouse')),
                ('Power_Supply_Unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Power_Supply_Unit')),
                ('Processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Processor')),
                ('Ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.RAM')),
                ('Speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Speaker')),
            ],
        ),
    ]
