# Generated by Django 3.0.8 on 2020-12-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0012_auto_20201205_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='Motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Motherboard'),
        ),
    ]
