# Generated by Django 3.0.8 on 2020-12-06 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System', '0013_auto_20201206_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='build',
            name='Motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Motherboard'),
        ),
    ]
