# Generated by Django 3.0.8 on 2020-12-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0014_auto_20201206_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='Motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Motherboard'),
        ),
    ]
