# Generated by Django 3.0.8 on 2020-12-06 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System', '0015_auto_20201206_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='Motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Motherboard'),
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Build', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Build')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
