# Generated by Django 3.0.8 on 2020-12-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0016_auto_20201206_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referrals',
            old_name='user',
            new_name='To',
        ),
        migrations.AddField(
            model_name='referrals',
            name='From',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='Motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Motherboard'),
        ),
    ]
